apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: att1-may14-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/att1-may14-1:1241d5bdb95a2077ac33fd26c0a7ce1aa3023a5d@sha256:3a61b057ce7cc9bd59ce609f28b3672f521b7406b9722657f8eba090c91b842b # use pre-built to bootstrap
          name: app-inference
